---
- name: Import users tasks
  ansible.builtin.import_tasks: tasks/users.yml

- name: Import PHP tasks
  ansible.builtin.import_tasks: tasks/php.yml

- name: Import Nginx tasks
  ansible.builtin.import_tasks: tasks/nginx.yml

- name: Import files tasks
  ansible.builtin.import_tasks: tasks/files.yml

- name: Import database tasks
  ansible.builtin.import_tasks: tasks/database.yml

- name: Import WordPress tasks
  ansible.builtin.import_tasks: tasks/wordpress.yml

- name: Import cron tasks
  ansible.builtin.import_tasks: tasks/cron.yml
